"use client";

import Link from "next/link";

export default function PokeList() {
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };
  return (
    <main className="px-6 space-y-6 relative">
      <button
        className="fixed btn btn-circle bottom-4 right-4"
        onClick={() => scrollToTop()}
      >
        上へ
      </button>
      <h1 className="text-2xl font-bold">
        Pokedleに収録されているモンスター一覧
      </h1>

      <h2 className="text-lg font-bold">目次</h2>
      <ul className="list-disc">
        <li>
          <Link href="#1" className="link link-primary">
            赤・緑・青・ピカチュウ
          </Link>
        </li>
        <li>
          <Link href="#2" className="link link-primary">
            金・銀・クリスタル
          </Link>
        </li>
        <li>
          <Link href="#3" className="link link-primary">
            ルビー・サファイア・ファイアレッド・リーフグリーン・エメラルド
          </Link>
        </li>
        <li>
          <Link href="#4" className="link link-primary">
            ダイヤモンド・パール・プラチナ・ハートゴールド・ソウルシルバー
          </Link>
        </li>
        <li>
          <Link href="#5" className="link link-primary">
            ブラック・ホワイト・ブラック2・ホワイト2
          </Link>
        </li>
        <li>
          <Link href="#6" className="link link-primary">
            X・Y・オメガルビー・アルファサファイア
          </Link>
        </li>
        <li>
          <Link href="#7" className="link link-primary">
            サン・ムーン・ウルトラサン・ウルトラムーン・Let’s Go!
            ピカチュウ・イーブイ
          </Link>
        </li>
        <li>
          <Link href="#8" className="link link-primary">
            ソード・シールド・ブリリアントダイヤモンド・シャイニングパール・LEGENDS
            アルセウス
          </Link>
        </li>
        <li>
          <Link href="#9" className="link link-primary">
            スカーレット・バイオレット
          </Link>
        </li>
      </ul>

      <h2 id="1" className="text-lg font-bold">
        赤・緑・青・ピカチュウ
      </h2>
      <ul className="list-disc">
        <li>フシギダネ</li>
        <li>フシギソウ</li>
        <li>フシギバナ</li>
        <li>リザードン</li>
        <li>カメックス</li>
        <li>キャタピー</li>
        <li>トランセル</li>
        <li>バタフリー</li>
        <li>ピジョット</li>
        <li>オニスズメ</li>
        <li>オニドリル</li>
        <li>アーボック</li>
        <li>ピカチュウ</li>
        <li>ライチュウ</li>
        <li>サンドパン</li>
        <li>ニドラン♀</li>
        <li>ニドリーナ</li>
        <li>ニドクイン</li>
        <li>ニドラン♂</li>
        <li>ニドリーノ</li>
        <li>ニドキング</li>
        <li>キュウコン</li>
        <li>ゴルバット</li>
        <li>ナゾノクサ</li>
        <li>クサイハナ</li>
        <li>ラフレシア</li>
        <li>パラセクト</li>
        <li>モルフォン</li>
        <li>ダグトリオ</li>
        <li>ペルシアン</li>
        <li>ゴルダック</li>
        <li>オコリザル</li>
        <li>ウインディ</li>
        <li>ニョロボン</li>
        <li>ユンゲラー</li>
        <li>フーディン</li>
        <li>ワンリキー</li>
        <li>ゴーリキー</li>
        <li>カイリキー</li>
        <li>マダツボミ</li>
        <li>ウツボット</li>
        <li>メノクラゲ</li>
        <li>ドククラゲ</li>
        <li>イシツブテ</li>
        <li>ゴローニャ</li>
        <li>ギャロップ</li>
        <li>レアコイル</li>
        <li>ドードリオ</li>
        <li>ベトベター</li>
        <li>ベトベトン</li>
        <li>シェルダー</li>
        <li>パルシェン</li>
        <li>スリーパー</li>
        <li>キングラー</li>
        <li>ビリリダマ</li>
        <li>マルマイン</li>
        <li>サワムラー</li>
        <li>エビワラー</li>
        <li>ベロリンガ</li>
        <li>マタドガス</li>
        <li>サイホーン</li>
        <li>モンジャラ</li>
        <li>トサキント</li>
        <li>アズマオウ</li>
        <li>ヒトデマン</li>
        <li>スターミー</li>
        <li>バリヤード</li>
        <li>ストライク</li>
        <li>ルージュラ</li>
        <li>ケンタロス</li>
        <li>コイキング</li>
        <li>ギャラドス</li>
        <li>シャワーズ</li>
        <li>サンダース</li>
        <li>ブースター</li>
        <li>オムナイト</li>
        <li>オムスター</li>
        <li>カブトプス</li>
        <li>フリーザー</li>
        <li>ファイヤー</li>
        <li>ミニリュウ</li>
        <li>ハクリュー</li>
        <li>カイリュー</li>
        <li>ミュウツー</li>
      </ul>
      <h2 id="2" className="text-lg font-bold">
        金・銀・クリスタル
      </h2>
      <ul className="list-disc">
        <li>チコリータ</li>
        <li>ベイリーフ</li>
        <li>メガニウム</li>
        <li>ヒノアラシ</li>
        <li>マグマラシ</li>
        <li>バクフーン</li>
        <li>アリゲイツ</li>
        <li>オーダイル</li>
        <li>ヨルノズク</li>
        <li>レディアン</li>
        <li>アリアドス</li>
        <li>クロバット</li>
        <li>チョンチー</li>
        <li>ランターン</li>
        <li>トゲチック</li>
        <li>ネイティオ</li>
        <li>デンリュウ</li>
        <li>キレイハナ</li>
        <li>ウソッキー</li>
        <li>ニョロトノ</li>
        <li>ヒマナッツ</li>
        <li>ヤンヤンマ</li>
        <li>ブラッキー</li>
        <li>ヤミカラス</li>
        <li>ヤドキング</li>
        <li>アンノーン</li>
        <li>ソーナンス</li>
        <li>キリンリキ</li>
        <li>クヌギダマ</li>
        <li>フォレトス</li>
        <li>グライガー</li>
        <li>ハガネール</li>
        <li>グランブル</li>
        <li>ハリーセン</li>
        <li>ヘラクロス</li>
        <li>マグマッグ</li>
        <li>マグカルゴ</li>
        <li>テッポウオ</li>
        <li>デリバード</li>
        <li>マンタイン</li>
        <li>エアームド</li>
        <li>キングドラ</li>
        <li>ドンファン</li>
        <li>ポリゴン2</li>
        <li>カポエラー</li>
        <li>ムチュール</li>
        <li>エレキッド</li>
        <li>ミルタンク</li>
        <li>ヨーギラス</li>
        <li>サナギラス</li>
        <li>バンギラス</li>
      </ul>
      <h2 id="3" className="text-lg font-bold">
        ルビー・サファイア・ファイアレッド・リーフグリーン・エメラルド
      </h2>
      <ul className="list-disc">
        <li>ジュプトル</li>
        <li>ジュカイン</li>
        <li>ワカシャモ</li>
        <li>バシャーモ</li>
        <li>ミズゴロウ</li>
        <li>ヌマクロー</li>
        <li>ラグラージ</li>
        <li>ジグザグマ</li>
        <li>マッスグマ</li>
        <li>カラサリス</li>
        <li>アゲハント</li>
        <li>ドクケイル</li>
        <li>ハスブレロ</li>
        <li>ルンパッパ</li>
        <li>ダーテング</li>
        <li>オオスバメ</li>
        <li>ペリッパー</li>
        <li>サーナイト</li>
        <li>アメモース</li>
        <li>キノガッサ</li>
        <li>ヤルキモノ</li>
        <li>ケッキング</li>
        <li>テッカニン</li>
        <li>ゴニョニョ</li>
        <li>バクオング</li>
        <li>マクノシタ</li>
        <li>ハリテヤマ</li>
        <li>エネコロロ</li>
        <li>ボスゴドラ</li>
        <li>チャーレム</li>
        <li>ライボルト</li>
        <li>バルビート</li>
        <li>イルミーゼ</li>
        <li>マルノーム</li>
        <li>サメハダー</li>
        <li>ホエルオー</li>
        <li>ブーピッグ</li>
        <li>パッチール</li>
        <li>ナックラー</li>
        <li>ビブラーバ</li>
        <li>フライゴン</li>
        <li>チルタリス</li>
        <li>ザングース</li>
        <li>ハブネーク</li>
        <li>ルナトーン</li>
        <li>ソルロック</li>
        <li>ドジョッチ</li>
        <li>シザリガー</li>
        <li>ネンドール</li>
        <li>ユレイドル</li>
        <li>アーマルド</li>
        <li>ミロカロス</li>
        <li>カクレオン</li>
        <li>カゲボウズ</li>
        <li>ジュペッタ</li>
        <li>サマヨール</li>
        <li>トロピウス</li>
        <li>ユキワラシ</li>
        <li>オニゴーリ</li>
        <li>タマザラシ</li>
        <li>トドグラー</li>
        <li>トドゼルガ</li>
        <li>ハンテール</li>
        <li>サクラビス</li>
        <li>ジーランス</li>
        <li>ボーマンダ</li>
        <li>メタグロス</li>
        <li>レジロック</li>
        <li>レジアイス</li>
        <li>レジスチル</li>
        <li>ラティアス</li>
        <li>ラティオス</li>
        <li>カイオーガ</li>
        <li>グラードン</li>
        <li>レックウザ</li>
        <li>デオキシス</li>
      </ul>
      <h2 id="4" className="text-lg font-bold">
        ダイヤモンド・パール・プラチナ・ハートゴールド・ソウルシルバー
      </h2>
      <ul className="list-disc">
        <li>ハヤシガメ</li>
        <li>ドダイトス</li>
        <li>モウカザル</li>
        <li>ゴウカザル</li>
        <li>ポッチャマ</li>
        <li>ポッタイシ</li>
        <li>エンペルト</li>
        <li>ムクバード</li>
        <li>ムクホーク</li>
        <li>コロボーシ</li>
        <li>コロトック</li>
        <li>レントラー</li>
        <li>ロズレイド</li>
        <li>ズガイドス</li>
        <li>ラムパルド</li>
        <li>タテトプス</li>
        <li>トリデプス</li>
        <li>ミノムッチ</li>
        <li>ミノマダム</li>
        <li>ガーメイル</li>
        <li>ミツハニー</li>
        <li>ビークイン</li>
        <li>フローゼル</li>
        <li>チェリンボ</li>
        <li>カラナクシ</li>
        <li>トリトドン</li>
        <li>エテボース</li>
        <li>フワライド</li>
        <li>ミミロップ</li>
        <li>ムウマージ</li>
        <li>ドンカラス</li>
        <li>ニャルマー</li>
        <li>ブニャット</li>
        <li>リーシャン</li>
        <li>スカンプー</li>
        <li>スカタンク</li>
        <li>ドーミラー</li>
        <li>ドータクン</li>
        <li>ガブリアス</li>
        <li>ヒポポタス</li>
        <li>カバルドン</li>
        <li>ドラピオン</li>
        <li>グレッグル</li>
        <li>ドクロッグ</li>
        <li>マスキッパ</li>
        <li>ケイコウオ</li>
        <li>ネオラント</li>
        <li>ユキカブリ</li>
        <li>ユキノオー</li>
        <li>マニューラ</li>
        <li>ジバコイル</li>
        <li>ベロベルト</li>
        <li>ドサイドン</li>
        <li>モジャンボ</li>
        <li>エレキブル</li>
        <li>ブーバーン</li>
        <li>トゲキッス</li>
        <li>メガヤンマ</li>
        <li>リーフィア</li>
        <li>グレイシア</li>
        <li>グライオン</li>
        <li>ポリゴンZ</li>
        <li>エルレイド</li>
        <li>ダイノーズ</li>
        <li>ヨノワール</li>
        <li>ユキメノコ</li>
        <li>エムリット</li>
        <li>ディアルガ</li>
        <li>ヒードラン</li>
        <li>レジギガス</li>
        <li>ギラティナ</li>
        <li>クレセリア</li>
        <li>ダークライ</li>
        <li>アルセウス</li>
      </ul>
      <h2 id="5" className="text-lg font-bold">
        ブラック・ホワイト・ブラック2・ホワイト2
      </h2>
      <ul className="list-disc">
        <li>ビクティニ</li>
        <li>ツタージャ</li>
        <li>ジャノビー</li>
        <li>ジャローダ</li>
        <li>チャオブー</li>
        <li>エンブオー</li>
        <li>ミジュマル</li>
        <li>フタチマル</li>
        <li>ダイケンキ</li>
        <li>ミルホッグ</li>
        <li>ヨーテリー</li>
        <li>ハーデリア</li>
        <li>ムーランド</li>
        <li>チョロネコ</li>
        <li>レパルダス</li>
        <li>ヤナッキー</li>
        <li>バオッキー</li>
        <li>ヒヤッキー</li>
        <li>ムシャーナ</li>
        <li>ハトーボー</li>
        <li>ケンホロウ</li>
        <li>ゼブライカ</li>
        <li>ギガイアス</li>
        <li>ココロモリ</li>
        <li>モグリュー</li>
        <li>ドリュウズ</li>
        <li>ドッコラー</li>
        <li>ドテッコツ</li>
        <li>ローブシン</li>
        <li>ガマゲロゲ</li>
        <li>ハハコモリ</li>
        <li>ペンドラー</li>
        <li>エルフーン</li>
        <li>ドレディア</li>
        <li>ワルビアル</li>
        <li>ダルマッカ</li>
        <li>ヒヒダルマ</li>
        <li>マラカッチ</li>
        <li>イシズマイ</li>
        <li>イワパレス</li>
        <li>ズルズキン</li>
        <li>シンボラー</li>
        <li>デスカーン</li>
        <li>プロトーガ</li>
        <li>アバゴーラ</li>
        <li>アーケオス</li>
        <li>ヤブクロン</li>
        <li>ダストダス</li>
        <li>ゾロアーク</li>
        <li>チラーミィ</li>
        <li>チラチーノ</li>
        <li>ゴチルゼル</li>
        <li>ランクルス</li>
        <li>コアルヒー</li>
        <li>バニプッチ</li>
        <li>バニリッチ</li>
        <li>バイバニラ</li>
        <li>メブキジカ</li>
        <li>シュバルゴ</li>
        <li>タマゲタケ</li>
        <li>モロバレル</li>
        <li>ブルンゲル</li>
        <li>ママンボウ</li>
        <li>デンチュラ</li>
        <li>テッシード</li>
        <li>ナットレイ</li>
        <li>ギギギアル</li>
        <li>シビシラス</li>
        <li>シビビール</li>
        <li>シビルドン</li>
        <li>ランプラー</li>
        <li>シャンデラ</li>
        <li>オノノクス</li>
        <li>クマシュン</li>
        <li>ツンベアー</li>
        <li>フリージオ</li>
        <li>チョボマキ</li>
        <li>アギルダー</li>
        <li>コジョフー</li>
        <li>コジョンド</li>
        <li>クリムガン</li>
        <li>キリキザン</li>
        <li>バッフロン</li>
        <li>ウォーグル</li>
        <li>バルチャイ</li>
        <li>バルジーナ</li>
        <li>クイタラン</li>
        <li>アイアント</li>
        <li>サザンドラ</li>
        <li>ウルガモス</li>
        <li>コバルオン</li>
        <li>テラキオン</li>
        <li>ビリジオン</li>
        <li>トルネロス</li>
        <li>ボルトロス</li>
        <li>ランドロス</li>
        <li>ケルディオ</li>
        <li>メロエッタ</li>
        <li>ゲノセクト</li>
      </ul>
      <h2 id="6" className="text-lg font-bold">
        X・Y・オメガルビー・アルファサファイア
      </h2>
      <ul className="list-disc">
        <li>ハリマロン</li>
        <li>ハリボーグ</li>
        <li>ブリガロン</li>
        <li>テールナー</li>
        <li>ゲコガシラ</li>
        <li>ゲッコウガ</li>
        <li>ヒノヤコマ</li>
        <li>コフキムシ</li>
        <li>コフーライ</li>
        <li>カエンジシ</li>
        <li>フラエッテ</li>
        <li>メェークル</li>
        <li>ゴーゴート</li>
        <li>ヤンチャム</li>
        <li>トリミアン</li>
        <li>ニャスパー</li>
        <li>ニダンギル</li>
        <li>ギルガルド</li>
        <li>シュシュプ</li>
        <li>フレフワン</li>
        <li>ペロッパフ</li>
        <li>ペロリーム</li>
        <li>マーイーカ</li>
        <li>カラマネロ</li>
        <li>ガメノデス</li>
        <li>ドラミドロ</li>
        <li>ウデッポウ</li>
        <li>ブロスター</li>
        <li>エリキテル</li>
        <li>エレザード</li>
        <li>ガチゴラス</li>
        <li>アマルルガ</li>
        <li>ニンフィア</li>
        <li>ルチャブル</li>
        <li>ヌメルゴン</li>
        <li>クレッフィ</li>
        <li>オーロット</li>
        <li>バケッチャ</li>
        <li>パンプジン</li>
        <li>カチコール</li>
        <li>クレベース</li>
        <li>オンバット</li>
        <li>オンバーン</li>
        <li>ゼルネアス</li>
        <li>イベルタル</li>
      </ul>
      <h2 id="7" className="text-lg font-bold">
        サン・ムーン・ウルトラサン・ウルトラムーン・Let’s Go!
        ピカチュウ・イーブイ
      </h2>
      <ul className="list-disc">
        <li>フクスロー</li>
        <li>ニャヒート</li>
        <li>ガオガエン</li>
        <li>オシャマリ</li>
        <li>アシレーヌ</li>
        <li>ケララッパ</li>
        <li>ドデカバシ</li>
        <li>ヤングース</li>
        <li>デカグース</li>
        <li>アゴジムシ</li>
        <li>デンヂムシ</li>
        <li>クワガノン</li>
        <li>マケンカニ</li>
        <li>ケケンカニ</li>
        <li>オドリドリ</li>
        <li>アブリボン</li>
        <li>ルガルガン</li>
        <li>ドヒドイデ</li>
        <li>ドロバンコ</li>
        <li>バンバドロ</li>
        <li>ラランテス</li>
        <li>マシェード</li>
        <li>ヤトウモリ</li>
        <li>ヌイコグマ</li>
        <li>キテルグマ</li>
        <li>アママイコ</li>
        <li>アマージョ</li>
        <li>キュワワー</li>
        <li>コソクムシ</li>
        <li>シロデスナ</li>
        <li>ナマコブシ</li>
        <li>ネッコアラ</li>
        <li>バクガメス</li>
        <li>トゲデマル</li>
        <li>ミミッキュ</li>
        <li>ハギギシリ</li>
        <li>ジジーロン</li>
        <li>ジャランゴ</li>
        <li>コスモッグ</li>
        <li>コスモウム</li>
        <li>ソルガレオ</li>
        <li>ルナアーラ</li>
        <li>ウツロイド</li>
        <li>テッカグヤ</li>
        <li>カミツルギ</li>
        <li>ネクロズマ</li>
        <li>アーゴヨン</li>
        <li>ズガドーン</li>
        <li>メルメタル</li>
      </ul>
      <h2 id="8" className="text-lg font-bold">
        ソード・シールド・ブリリアントダイヤモンド・シャイニングパール・LEGENDS
        アルセウス
      </h2>
      <ul className="list-disc">
        <li>バチンキー</li>
        <li>ラビフット</li>
        <li>ジメレオン</li>
        <li>ホシガリス</li>
        <li>ヨクバリス</li>
        <li>アオガラス</li>
        <li>サッチムシ</li>
        <li>レドームシ</li>
        <li>ワタシラガ</li>
        <li>カジリガメ</li>
        <li>パルスワン</li>
        <li>トロッゴン</li>
        <li>カジッチュ</li>
        <li>タルップル</li>
        <li>サダイジャ</li>
        <li>サシカマス</li>
        <li>マルヤクデ</li>
        <li>オトスパス</li>
        <li>ポットデス</li>
        <li>ブリムオン</li>
        <li>オーロンゲ</li>
        <li>サニゴーン</li>
        <li>バリコオル</li>
        <li>デスバーン</li>
        <li>マホイップ</li>
        <li>タイレーツ</li>
        <li>バチンウニ</li>
        <li>コオリッポ</li>
        <li>イエッサン</li>
        <li>ドラメシヤ</li>
        <li>ドラパルト</li>
        <li>ザマゼンタ</li>
        <li>ウーラオス</li>
        <li>レジエレキ</li>
        <li>レジドラゴ</li>
        <li>ブリザポス</li>
        <li>レイスポス</li>
        <li>イダイトウ</li>
        <li>ハリーマン</li>
        <li>ラブトロス</li>
      </ul>
      <h2 id="9" className="text-lg font-bold">
        スカーレット・バイオレット
      </h2>
      <ul className="list-disc">
        <li>ニャローテ</li>
        <li>アチゲータ</li>
        <li>ウェルカモ</li>
        <li>ワナイダー</li>
        <li>マメバッタ</li>
        <li>パーモット</li>
        <li>パピモッチ</li>
        <li>オリーニョ</li>
        <li>オリーヴァ</li>
        <li>イキリンコ</li>
        <li>ハラバリー</li>
        <li>タギングル</li>
        <li>ノノクラゲ</li>
        <li>リククラゲ</li>
        <li>カプサイジ</li>
        <li>カヌチャン</li>
        <li>ウミトリオ</li>
        <li>オトシドリ</li>
        <li>ナミイルカ</li>
        <li>イルカマン</li>
        <li>モトトカゲ</li>
        <li>キラフロル</li>
        <li>ハカドッグ</li>
        <li>カラミンゴ</li>
        <li>アルクジラ</li>
        <li>ハルクジラ</li>
        <li>ミガルーサ</li>
        <li>シャリタツ</li>
        <li>コノヨザル</li>
        <li>リキキリン</li>
        <li>ノココッチ</li>
        <li>ドドゲザン</li>
        <li>セグレイブ</li>
        <li>コレクレー</li>
        <li>サーフゴー</li>
        <li>パオジアン</li>
        <li>ディンルー</li>
        <li>コライドン</li>
        <li>ミライドン</li>
      </ul>
    </main>
  );
}
